version: '3.8'

services:
  nest:
    container_name: nest
    image: skazuki/alpine-node-yarn-install
    ports:
      - 24500:5000
    command: ["yarn", "start:dev"]
    restart: always
    volumes:
      - .:/node
    links:
      - db
    networks: 
      - sql-page
  db:
    container_name: db
    image: mysql:8.0
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    logging:
      driver: none
    networks:
      - sql-page
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    links:
      - db
    ports:
      - 24580:8080
    volumes:
      - ./adminer/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    logging:
      driver: none
    networks:
      - sql-page

networks:
  sql-page:
    external: true